conf_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('speakers/', include('speakers.urls')),

]

speakers/urls.py
from django.urls import path
from . import views

app_name = 'speakers'
urlpatterns = [
    path('', views.index, name='index'),
    # path('jado', views.jado)
    # path('<str:speaker_name>', views.create, name='create')
    path('create', views.create, name='create'),
    path('update', views.update, name='update'),
    path('delete', views.delete, name='delete')
]

speakers/models.py
from django.db import models

# Create your models here.
class Speaker(models.Model):
    name = models.CharField(max_length=200)

speakers/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms
class NewSpeaker(forms.Form):
    name = forms.CharField(label='Name')

spks = [
    'speaker 1',
    'speaker 2',
    'speaker 3',
    'speaker 4',
]
# Create your views here.

def index(request):
    return render(request, 'home.html', {
        'speakers': spks
    })

def create(request):
    if request.method == "POST":
        speaker = NewSpeaker(request.POST)
        if speaker.is_valid():
            cleaned_speaker = speaker.cleaned_data()
            spks.append(cleaned_data)

    return render(request, 'create.html', {
        'name': NewSpeaker()
    })
def update(req):
    return render(req, 'update.html')

def delete(req):
    return render(req, 'delete.html')

speakers/templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Speaker</title>
</head>
<body>
 <h1>Add New Speaker</h1> 
 <form action="{% url 'speakers:create' %}" method="post">
    {% csrf_token%}
    {{ name }}
    <input type="submit">
 </form>  
 <a href="{% url 'speakers:index' %}"> Back to speakers</a>
</body>
</html>

speakers/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Deleting a speaker</title>
</head>
<body>
    <h1>speaker deleted</h1>
</body>
</html>

speakers/templates/home.html
<!-- {% load static %} -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Conference App</title>
    <style>
        *{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: sans-serif;
        }
        body{
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            background-color: aqua;
            flex-direction: column;
        }
    </style>
</head>
<body>
    <h1>List of Speakers</h1>
    <div>
        <ul>
            {% for speaker in speakers %}
            <li>{{ speaker }}</li>
            {% endfor %}

        </ul>
    </div>

    <a href="{% url 'speakers:create' %}">create a speaker</a>
    <a href="{% url 'speakers:update' %}">Update the Lists</a>
    <a href="{% url 'speakers:delete' %}">Delete the speakers</a>
    
</body>
</html>

speakers/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>speakers</title>
</head>
<body>
<h1>updating speakers list</h1>
</body>
</html>